import { C } from "../data";

export const SCENARIOS = [
  {
    id: "hospital",
    type: "raw",
    icon: "🏥",
    title: "Hospital Waiting Times",
    hook: "You work for the NHS. Your job is to compare waiting times.",
    setup:
      "Patients in A&E are waiting to be seen. You collect waiting times from 15 patients at City Hospital. The data is in arrival order, not sorted order.",
    unit: "minutes",
    unitShort: "min",
    rawData: [67, 23, 41, 88, 15, 54, 31, 72, 19, 45, 60, 38, 80, 27, 52],
    sorted: [15, 19, 23, 27, 31, 38, 41, 45, 52, 54, 60, 67, 72, 80, 88],
    answer: { min: 15, q1: 27, median: 45, q3: 67, max: 88 },
    decisionText:
      "The median wait is 45 minutes, but the IQR is 40 minutes, so waiting times are quite inconsistent.",
    scaleMin: 0,
    scaleMax: 100,
  },
  {
    id: "science",
    type: "barchart",
    icon: "🔬",
    title: "Plant Growth Experiment",
    hook: "Scientists are testing two fertilisers to see which grows taller plants.",
    setup:
      "30 identical seedlings were treated with Fertiliser A and 30 with Fertiliser B. After 4 weeks, their heights were recorded.",
    unit: "cm",
    unitShort: "cm",
    answer: { min: 8, q1: 14, median: 19, q3: 25, max: 38 },
    answerB: { min: 11, q1: 18, median: 26, q3: 31, max: 41 },
    rows: [
      { interval: "0-5", freq: 1, cumFreq: 1 },
      { interval: "6-10", freq: 4, cumFreq: 5 },
      { interval: "11-15", freq: 8, cumFreq: 13 },
      { interval: "16-20", freq: 8, cumFreq: 21 },
      { interval: "21-25", freq: 5, cumFreq: 26 },
      { interval: "26-30", freq: 3, cumFreq: 29 },
      { interval: "31-35", freq: 0, cumFreq: 29 },
      { interval: "36-40", freq: 1, cumFreq: 30 },
    ],
    rowsB: [
      { interval: "0-5", freq: 0, cumFreq: 0 },
      { interval: "6-10", freq: 1, cumFreq: 1 },
      { interval: "11-15", freq: 3, cumFreq: 4 },
      { interval: "16-20", freq: 6, cumFreq: 10 },
      { interval: "21-25", freq: 7, cumFreq: 17 },
      { interval: "26-30", freq: 8, cumFreq: 25 },
      { interval: "31-35", freq: 4, cumFreq: 29 },
      { interval: "36-41", freq: 1, cumFreq: 30 },
    ],
    scaleMin: 0,
    scaleMax: 45,
  },
  {
    id: "delivery",
    type: "cumfreq",
    icon: "📦",
    title: "Delivery Times",
    hook: "You run a small business and customers are complaining about slow deliveries.",
    setup:
      "A courier company tracked how many days 60 parcels took to arrive. The results are shown as a cumulative frequency graph.",
    unit: "days",
    unitShort: "days",
    answer: { min: 1, q1: 3, median: 5, q3: 7, max: 12 },
    totalFreq: 60,
    cumFreqPoints: [
      [0, 0],
      [1, 0],
      [2, 3],
      [3, 15],
      [4, 24],
      [5, 30],
      [6, 38],
      [7, 45],
      [8, 51],
      [9, 55],
      [10, 57],
      [11, 59],
      [12, 60],
    ],
    readPoints: [
      { freq: 15, label: "Q1", value: 3, color: C.accent },
      { freq: 30, label: "Median", value: 5, color: C.text },
      { freq: 45, label: "Q3", value: 7, color: C.accent },
    ],
    decisionText:
      "The typical delivery time is 5 days, but 25% of parcels take longer than 7 days, which explains the customer complaints.",
    scaleMin: 0,
    scaleMax: 14,
  },
];